### ISSUE TITLE
CURLOPT_TCP_KEEPALIVE option is missing 

### ISSUE THREAD

**Issue by ElJaviLuki** [jpbarrette/curlpp#105]
[https://curl.haxx.se/libcurl/c/CURLOPT_TCP_KEEPALIVE.html](CURLOPT_TCP_KEEPALIVE)  exists and doing something like this:
`handle.setOpt(cURLpp::Options::KeepAlive(whatever))` has no effect...

That's all.

**Comment by sgallou** [comment]
I just added it in feature/AddTcpKeepAliveOption branch (commit 2e949a9c49eaaf873ed4d2356d6ed778b6002a17).
But I currently have no mean to test it. Can you test it and give result ? So I will be able to merge branch in develop branch.

**Comment by sgallou** [comment]
Hi @ElJaviLuki ,
did you test my changes ?
Thanks,

**Comment by sgallou** [comment]
Fixed by 2e949a9c49eaaf873ed4d2356d6ed778b6002a17
