### ISSUE TITLE
[question] status of CURLPP project

### ISSUE THREAD

**Issue by sbelsky** [jpbarrette/curlpp#11]
at this time:
1) there are 5 openned Issues and 3 PR. the oldest item was openned more than half a year ago.
2) some planned features (eg CMAKE support) were not fully implemented.
3) almost all files in master branch dated by 2009.

is this a "dead" project? does somebody really support it?

**Comment by jpbarrette** [comment]
It's not dead, but not very active. Mostly, I try to integrate changes that
people submit, but I no longer actively participate into this project. If
there's someone who wants push this project further, it would be my
pleasure to give curlpp's ownership to that person.

**Comment by sbelsky** [comment]
@jpbarrette i can take a care about cosmetic, some bugs and CM tasks. if only you will be agree to supervise and consult as a main ideologist.

**Comment by jpbarrette** [comment]
@sbelsky: It absolutely works with me. Welcome aboard!

**Comment by Nelson-numerical-software** [comment]
Does this project is  always living ?
no commit since one year
no bug ?
