### ISSUE TITLE
hiding cmd window while calling perform

### ISSUE THREAD

**Issue by Suresh3d** [jpbarrette/curlpp#114]
Hi,

I just started using curlpp for my project to make server calls . I noticed that while calling perform it is opening new cmd window and closing immediately. I really need to avoid this flashing cmd window as it shows many windows while performing many calls. Is there any way to avoid this ? 

I am building this project in windows 10.

**Comment by sgallou** [comment]
Hi,
Curlpp is a library and as far as I known, don't do any call to system. So I presume these cmd windows are coming from your application.
Did you test from a provided example ? See `examples` directory.
