### ISSUE TITLE
Warning during compilation

### ISSUE THREAD

**Issue by kometen** [jpbarrette/curlpp#12]
Hi. I'm using your nice wrapper in a C++ project pulling some XML-data from the web. The project is in eclipse (mars). When compiling I would get a warning. The fix was very simple, merely adding a */ to the end of the line.

    %>git diff
    diff --git a/include/curlpp/config.win32.h b/include/curlpp/config.win32.h
    index 1a67bc9..3dc90da 100644
    --- a/include/curlpp/config.win32.h
    +++ b/include/curlpp/config.win32.h
    @@ -2,7 +2,7 @@
     /* config.h.in    Generated from configure.ac by autoheader.   */
 
     /* Define when building curlpp itself */
    -/* DO NOT define or undefine this symbol if you are building from the IDE
    +/* DO NOT define or undefine this symbol if you are building from the IDE */
     /* using solution files for VC9. Project files define or undefine this from within the IDE */
     //#define BUILDING_CURLPP

**Comment by kometen** [comment]
This fix only requires */ to be added to line five of config.win32.h. Care to commit?

**Comment by jpbarrette** [comment]
Sorry, I was busy. Yes I'll submit as soon as I can.

**Comment by jpbarrette** [comment]
A fix has been checked-in. Closing this issue
