### ISSUE TITLE
Replace auto_ptr with either shared_ptr or unique_ptr

### ISSUE THREAD

**Issue by sanjayankur31** [jpbarrette/curlpp#13]
GCC6 has C++14 as default, and auto_ptr was deprecated in C++11. The suggestion is to port auto_ptr over to shared_ptr or unique_ptr as required. More information here: https://gcc.gnu.org/gcc-6/porting_to.html

Since Fedora 24 defaults to GCC6 and errors at the use of auto_ptr, curlpp doesn't currently build there. Bug here: https://bugzilla.redhat.com/show_bug.cgi?id=1307415

**Comment by infinity0** [comment]
GCC6 is not yet in Debian but will be soon, and there is already a pre-emptive "will-fail-to-build" bug [here](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=811959). It looks like people are already working on it so I will sit back and relax. :)

**Comment by infinity0** [comment]
Just as a note, GCC6 will be soon the default in Debian and curlpp has already been automatically removed from Debian testing because it doesn't build against it.

**Comment by cronnosli** [comment]
I have some services using this lib, so as soon as I upgraded to debian 9 those stop to work. Then I had change the auto_ptr to shared_ptr. Since that I had made several tests and seen to have no bugs related to this change.

**Comment by jpbarrette** [comment]
The change is available on branch named "c++11". Can you please try it? As soon as you give me the confirmation it works, I'll push in main branch.

**Comment by cronnosli** [comment]
HI @jpbarrette, it's working!
All tests are ok.
I think it's all good to go!

**Comment by jpbarrette** [comment]
Branch merged, issue should be fixed. Thanks everyone!
