### ISSUE TITLE
How to upload a binary file(examle: a image) by Form?

### ISSUE THREAD

**Issue by shaozhihua** [jpbarrette/curlpp#136]
hello sir,
I have already seen the examples: "example19.cpp",but I am a little confused,I don't know how to post a image by form ,should I use some fix options?
like 
formParts.push_back(new curlpp::FormParts::Content("filename", "/home/zsh/test.jpeg"));
and 
request.setOpt(new curlpp::options::HttpPost(formParts));
and 
request.perform();?
I wonder a specific code.I am not smart,thanks so much!

**Comment by zuixiaosanlang** [comment]
@shaozhihua 
hello, have you solved this ??

**Comment by zuixiaosanlang** [comment]
@shaozhihua 
hello, have you solved this ??

**Comment by shaozhihua** [comment]
@zuixiaosanlang 
没，最后放弃使用这个curlpp了，使用的curl和Qt中的QHttpMultiPart，就没用这个了。

**Comment by zuixiaosanlang** [comment]
@shaozhihua 
我也是用curl解决了，那我也放弃这个curlpp了。可能这个库还没完善好

**Comment by zuixiaosanlang** [comment]
@shaozhihua 
我也是用curl解决了，那我也放弃这个curlpp了。可能这个库还没完善好

**Comment by shaozhihua** [comment]
那我关闭这个issue了
