### ISSUE TITLE
cURLpp linker errors

### ISSUE THREAD

**Issue by oofsamy** [jpbarrette/curlpp#138]
Hey, I am compiling a program I've made that uses cURLpp, I linked libcURL as well so it shouldn't error for that. I added them to include directories as well, I'm horrible at C++ so I'm very confused
![image](https://user-images.githubusercontent.com/61066276/147370517-4aa1a3de-ed44-4cf8-97b2-f6a6d4d84ed5.png)

![image](https://user-images.githubusercontent.com/61066276/147370533-01464a69-10f9-4d2a-850a-7367bd38fae3.png)

**Comment by sgallou** [comment]
Hi,
your app doesn't find curlpp and libcurl when linking (includes are OK). Check that curlpp/libcurl libraries are well built, and check if the link step of your app well targets curlpp/libcurl binaries (.lib files).
Under MSVC2019, display project properties of your app ==> Linker ==> inputs ==> additional dependencies
