### ISSUE TITLE
How to download zip file

### ISSUE THREAD

**Issue by JTD420** [jpbarrette/curlpp#144]
I'm making an updater for my program but been really struggling at the final part of it!

I've got it going to two different links right now.
1 grabs the latest version number
the other is the current latest version download link in zip format.

Now I want to have it go to the Latest Download URL and download the zip to the users appdata directory in a folder that I've already created for my application.

How can I do this? No matter what I try I'm left with errors relating to converting from one type to another and I'm slowly loosing it. Getting close to giving up on trying to add this feature tbh lol

**Comment by JTD420** [comment]
ps apologies for opening this as an issue but I've read through the documentation and i really just don't know what else to do so was hoping I'd get some help here!

**Comment by JTD420** [comment]
Resolved!!! :)

**Comment by pete-the-dev** [comment]
How?!
I have been working on this and am also slowly losing my mind...
how did you do it?
