### ISSUE TITLE
Wrong RelativePath in curlpp.VC8.vcproj

### ISSUE THREAD

**Issue by ccdMuro** [jpbarrette/curlpp#18]
The files `LifetimeLibrary.cpp` and `PrivateMembers.cpp` are both located in `.\src\utilspp\` but the project points to `.\src\utilspp\singleton`

I got the compiler error message that neither could be found.

Solution: I changed the `RelativePath` in the file properties within VisualStudio, but i think changing the entry in the `curlpp.VC8.vcproj` file with a text editor will do the trick too.

**Comment by jpbarrette** [comment]
I just submitted the suggested fix. Thanks for the report!
