### ISSUE TITLE
How do I download this library

### ISSUE THREAD

**Issue by alexpanter** [jpbarrette/curlpp#19]
There are a lot of files, and I'm relatively new to C++.
The only thing that the front page tells me is to visit `https://github.com/jpbarrette/curlpp/`
for how to download. But I am already on this page, and it confuses me.

If someone could give me a hint, that would be hugely appreciated.
Thanks.

**Comment by yh42** [comment]
`git clone git@github.com:jpbarrette/curlpp.git`

**Comment by alexpanter** [comment]
thanks :)
