### ISSUE TITLE
There is no configure file

### ISSUE THREAD

**Issue by iRajul** [jpbarrette/curlpp#22]
I was trying to build this library on linux (CentOs) but unable to find configure file.

**Comment by Rasie1** [comment]
You should run ./autogen.sh at first. Then, configure will appear. 
However, right now it still won't build because it doesn't have correct c++ flags set (no -std=c++11)

**Comment by iRajul** [comment]
@Rasie1 Yeah jpbarrette told me to run `./autogen` and that build works on my Linux system.

**Comment by Shravan40** [comment]
What to do after running `./autogen.sh` ?

**Comment by jpbarrette** [comment]
There's an "INSTALL" file giving instructions on how to build, but
essentially :

autogen.sh && ./configure && make
