### ISSUE TITLE
example18.cpp HAVE_BOOST

### ISSUE THREAD

**Issue by Rasie1** [jpbarrette/curlpp#24]
After `./autogen.sh` and `./configure` and `make` project can't be built under Ubuntu 16.06. HAVE_BOOST is not defined when example18.cpp is compiled.

Why this check is even there?

**Comment by jpbarrette** [comment]
You're right there's a problem with the defines. I have a quick fix that just makes sure not to compile that file if don't have boost. This will be in the next release.
