### ISSUE TITLE
Unable to find LIB_CURL

### ISSUE THREAD

**Issue by ethanhs** [jpbarrette/curlpp#26]
I installed libcurl (v7.51) on Windows via CMake, with out any problems. It is installed in C:/Program Files (x86)/CURL, as expected. However, when I try to generate a project from cmake, it fails to find libcURL.

I'm at a loss to explain why it would fail like this...

Here is the log:

    -- Building for: Visual Studio 15 2017
        -- The C compiler identification is MSVC 19.10.24629.0
        -- The CXX compiler identification is MSVC 19.10.24629.0
        -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.24629/bin/HostX86/x86/cl.exe
        -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.24629/bin/HostX86/x86/cl.exe -- works
        -- Detecting C compiler ABI info
        -- Detecting C compiler ABI info - done
        -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.24629/bin/HostX86/x86/cl.exe
        -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.10.24629/bin/HostX86/x86/cl.exe -- works
        -- Detecting CXX compiler ABI info
        -- Detecting CXX compiler ABI info - done
        -- Detecting CXX compile features
        -- Detecting CXX compile features - done
        --      Using Sources From: C:/Users/<username>/Documents/gitter++/lib/curlpp/
        --      Putting all major output in: C:/Users/<username>/Documents/gitter++/lib/curlpp/build/
        --      Inputs of type .cpp at: C:/Users/<username>/Documents/gitter++/lib/curlpp/src/
        --      Inputs of type .h and .hpp at: C:/Users/<username>/Documents/gitter++/lib/curlpp/include/
        --      Inputs to be built as standalone examples are at: C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/
        --      Using Header Files:
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/EmptyType.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/singleton/LifetimeWithLongevity.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/singleton/SingletonHolder.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/singleton/LifetimeLibrary.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/singleton/CreationStatic.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/singleton/CreationUsingNew.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/singleton/LifetimeDefault.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/singleton/PrivateMembers.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/NullType.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/ThreadingSingle.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/Singleton.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/TypeTrait.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/clone_ptr.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/functor/MemFunHandler.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/functor/FunctorHandler.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/functor/Binder.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/functor/FunctorImpl.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/functor/Functor.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/TypeList.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/NonCopyable.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/SmartPtr.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/ThreadingFactoryMutex.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/utilspp/Functors.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/Exception.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/Option.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/Info.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/Easy.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/Form.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/Types.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/OptionBase.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/Infos.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/Options.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/Multi.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/internal/OptionContainerType.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/internal/global.h
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/internal/buildconfig.h
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/internal/OptionContainer.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/internal/SList.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/internal/CurlHandle.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/internal/OptionSetter.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/internal/OptionList.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/include/curlpp/cURLpp.hpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/autolink.h
        --      Using Source Files:
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/utilspp/PrivateMembers.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/utilspp/LifetimeLibrary.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/Form.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/Exception.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/Options.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/Option.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/Options.custom.ins
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/Info.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/Multi.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/OptionBase.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/internal/SList.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/internal/OptionSetter.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/internal/OptionList.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/internal/CurlHandle.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/Infos.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/Easy.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/src/curlpp/cURLpp.cpp
        --      Using Example Files:
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example00.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example01.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example02.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example03.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example04.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example05.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example06.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example07.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example08.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example09.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example10.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example11.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example12.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example13.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example14.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example16.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example15.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example17.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example18.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example19.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example20.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example21.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example22.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example23.cpp
        --              C:/Users/<username>/Documents/gitter++/lib/curlpp/examples/example24.cpp
        -- Looking for CURL
        -- Could NOT find CURL (missing:  CURL_LIBRARY CURL_INCLUDE_DIR)
        CMake Error at C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:148 (message):
        Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR)
        Call Stack (most recent call first):
        C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.6/Modules/FindPackageHandleStandardArgs.cmake:388 (_FPHSA_FAILURE_MESSAGE)
        C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/Common7/IDE/CommonExtensions/Microsoft/CMake/CMake/share/cmake-3.6/Modules/FindCURL.cmake:61 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
        CMakeLists.txt:138 (find_package)
    
    
        -- Configuring incomplete, errors occurred!
        See also "C:/Users/<username>/Documents/gitter++/lib/curlpp/build/CMakeFiles/CMakeOutput.log".
    
     

Thanks for any advice/guidance you could provide.

**Comment by jpbarrette** [comment]
Check the answer from: http://stackoverflow.com/questions/34914944/could-not-find-curl-missing-curl-library-curl-include-dir-on-cmake

**Comment by ethanhs** [comment]
Hi. I've read that solution. However, I ran the install target for it as the answer suggests, and so something must be broken, as I believe it should find it then, but it isnt.

**Comment by ethanhs** [comment]
actually I filed a bug. It appears if you use CURL'S Cmake file, it doesnt install anywhere cmake looks by default, you have to add the path.

**Comment by jpbarrette** [comment]
Closing this issue since the problem seems solved. Can you please link to the bug report you filed?

**Comment by ethanhs** [comment]
https://gitlab.kitware.com/cmake/cmake/issues/16451
