### ISSUE TITLE
curlpp/internal/../internal/../config.win32.h:64:0: warning: "STDC_HEADERS" redefined

### ISSUE THREAD

**Issue by MatthewButterfly** [jpbarrette/curlpp#27]
curlpp/internal/../internal/../config.win32.h:64:0: warning: "STDC_HEADERS" redefined
#define STDC_HEADERS

**Comment by jpbarrette** [comment]
Can you provide a bit more information on how you built curlpp? Which compiler are you using?

**Comment by jpbarrette** [comment]
I had a look at that config file and I really think I should get rid of it. I want to verify the state of the cmake integration, but I might use that opportunity to get rid of that file that doesn't really make sense at this point (and is outdated).

**Comment by jpbarrette** [comment]
Please try "develop" branch. This branch only has a cmake configuration and handles better all platforms configurations.
