### ISSUE TITLE
Android Support

### ISSUE THREAD

**Issue by vinodshinde** [jpbarrette/curlpp#29]
Is it possible to build this library for android?

**Comment by jpbarrette** [comment]
I never tried, but here's some pointers if you want to try:

1. You'll have to be able to build/link with libcURL. Here's a starting point: https://github.com/gcesarmza/curl-android-ios
2. Then the big thing to worry is if Android got C++ STL support:
    - https://developer.android.com/ndk/guides/cpp-support.html
    - http://stackoverflow.com/questions/4893403/cant-include-c-headers-like-vector-in-android-ndk

Tell me if you managed to make it work.

**Comment by jpbarrette** [comment]
Closing this issue, reopen if you still have problems
