### ISSUE TITLE
dll import error

### ISSUE THREAD

**Issue by OriginLive** [jpbarrette/curlpp#30]
hello, i get a bunch of errors using curlpp
\curlpp\internal\optioncontainer.inl(39): error C2491: 'curlpp::internal::OptionContainer<OptionType>::OptionContainer': definition of dllimport function not allowed

using visual studio 2015

**Comment by OriginLive** [comment]
https://msdn.microsoft.com/en-us/library/62688esh.aspx
this is the issue

**Comment by jpbarrette** [comment]
I'll have a look next week. Thanks for the report (and the extra info)!

**Comment by OriginLive** [comment]
Well the thing is, i can't use curlpp because i can't get the mangling to talk to eachother. I can compile curl and curlpp with mingw, but i can't use mingw in my code because i'm using threads. And i can't use visual studio with curlpp because it can't find the target. So fixing the dll symbols issue would fix the broken vs15 compiling

**Comment by jpbarrette** [comment]
I'll have a look at this this week.

**Comment by OriginLive** [comment]
C:\Users\Origin\AppData\Local\Temp\cc3dF8Ob.o: In function `curlpp::OptionTrait<bool, (CURLoption)41>::OptionTrait(bool const&)':
D:/apps/sample/testing/SpideR/libs/curlpp/Option.inl:124: undefined reference to `__imp__ZTVN6curlpp11OptionTraitIbL10CURLoption41EEE'
great, because i can't get it to work using mingw

**Comment by OriginLive** [comment]
Any progress? Still can't get it to compile right, what's the official way of doing it with mingw?

**Comment by jpbarrette** [comment]
Can you try the cmake-cleanup branch? This branch completely transfered into cmake build system and I cleaned up the linking + template definitions. I'll give it a try myself today.

**Comment by jpbarrette** [comment]
I'll eventually have more documention about building on windows, which should be simpler soon.

**Comment by OriginLive** [comment]
Getting linker errors, can't get it to fit with curl

**Comment by jpbarrette** [comment]
Can you put here the details of what you've done and the actual error messages?

**Comment by OriginLive** [comment]
I tried curl-master and curl 7.52.1
I've generated files with cmake and also tried using the already premade .sln files. Both debug and runnable.

Then i've used cmake on curlpp and set the include and library build.
This is how the errors mostly look like, it seems there's a linker error as it cannot unmangle the names.
https://ideone.com/xephnx

**Comment by jpbarrette** [comment]
As previously said, can you please try the "feature/cmake-cleanup" branch, which fixes some issues with cmake? 

https://github.com/jpbarrette/curlpp/tree/feature/cmake-cleanup

cmake config file on master branch doesn't take into consideration the defines set up in buildconfig.h, so you'll need to switch on "feature/cmake-cleanup" branch to have a cmake config file which now has a better configuration for visual studio.

**Comment by OriginLive** [comment]
I have used the specified branch, this is the cmake file:
https://ideone.com/wpVeE5

**Comment by jpbarrette** [comment]
I think it will be easier for you if you just use nuget to get an already compiled curlpp. As mentionned on nuget's webpage:

> NuGet is the package manager for the Microsoft development platform including .NET. The NuGet client tools provide the ability to produce and consume packages. The NuGet Gallery is the central package repository used by all package authors and consumers.
> 
> When you use NuGet to install a package, it copies the library files to your solution and automatically updates your project (add references, change config files, etc.). If you remove a package, NuGet reverses whatever changes it made so that no clutter is left.
> 
> To learn more about the NuGet Gallery project and see who has contributed, see the About the Gallery page.

Here's a tutorial on using nuget: https://docs.microsoft.com/en-us/nuget/quickstart/use-a-package. Also, here's an available curlpp package for nuget (note that it's an unofficial distribution of curlpp): https://www.nuget.org/packages/curlpp/

If you really want to build curlpp by yourself, be aware that CMakeLists.txt isn't a script, but a configuration file that cmake program uses. If you want more details on cmake, please read the following: https://cmake.org/runningcmake/

Here's how you could build curlpp through cmake:

    # make sure cmake is installed: https://cmake.org/download/
    cd /d mydrive:\path\to\curlpp
    mkdir build
    cd build
    
    # NOTEs on CMAKE_PREFIX_PATH (since CMake 2.6.0) This is used when searching for 
    # include files, binaries, or libraries using either the FIND_PACKAGE(), FIND_PATH(), 
    # FIND_PROGRAM(), or FIND_LIBRARY() commands. For each path in the CMAKE_PREFIX_PATH 
    # list, CMake will check "PATH/include" and "PATH" when FIND_PATH() is called, "PATH/bin" 
    # and "PATH" when FIND_PROGRAM() is called, and "PATH/lib" and "PATH" when FIND_LIBRARY() 
    # is called. See the documentation for FIND_PACKAGE(), FIND_LIBRARY(), FIND_PATH(), and 
    # FIND_PROGRAM() for more details.
    
    # will create the msvc solutions
    cmake -DCMAKE_PREFIX_PATH=mydrive:\path\to\built-curl
    # you can either open curlpp.sln in visual studio, or
    # you can just run msbuild.exe as shown below. 
    
    # msbuild.exe will actually compile curlpp
    msbuild curlpp.sln

I'm closing this issue because this doesn't seem to be an issue with the library itself.

**Comment by OriginLive** [comment]
Hello, i got the project to compile, the problem was i was trying to link the static curl library, instead of dynamic one. Nowhere in any guide was there written that it's expecting a dll, hence the troubles I've had. I finally got it to compile now and it works fine :)
In the cmake, i see you have the options of static linker flags, is it possible to get the static library out?
