### ISSUE TITLE
make failed after cmake ..

### ISSUE THREAD

**Issue by Shravan40** [jpbarrette/curlpp#31]
I am trying to build curlpp locally on machine, using cmake version 3.2 in following steps.

1. `git clone git@github.com:jpbarrette/curlpp.git`
2. `cd curlpp && mkdir build && cd build && cmake ..`
3. `make`
and it fails here, Please find the [build log ](https://gist.github.com/Shravan40/0f894ba520f06ab33664fa83b3394f51)

And any possible solution to this.

**Comment by jpbarrette** [comment]
CMake support still needs some work. I'll try to have a look at you current problem next week. Meanwhile, can't you just use the autogen.sh script? This will generate the required makefiles.

https://github.com/jpbarrette/curlpp/issues/22

**Comment by Shravan40** [comment]
Issue number 22 exact replica of mine. I followed the steps suggested there but it didn't work for me. 

I have added the flag `set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11")` in file `CmakeLists.txt` but no luck.

**Comment by jpbarrette** [comment]
Can you please describe pour platform?

**Comment by jpbarrette** [comment]
I don't have access to the repository right now (I'm on vacation). But can you try the following answer: http://stackoverflow.com/a/37631452

cmake_minimum_required(VERSION 3.1)
set(CMAKE_CXX_STANDARD 11) # C++11...
set(CMAKE_CXX_STANDARD_REQUIRED ON) #...is required...
set(CMAKE_CXX_EXTENSIONS OFF) #...without compiler extensions like gnu++11

**Comment by Shravan40** [comment]
Here is my platform details.
```
┌─[shravan40@Shravan] - [~] - [Fri Dec 23, 03:54]
└─[$] <> uname -a
Linux Shravan 4.8.0-1-amd64 #1 SMP Debian 4.8.5-1 (2016-10-28) x86_64 GNU/Linux
┌─[shravan40@Shravan] - [~] - [Fri Dec 23, 03:54]

```
I have tried this aproach many time but it didn't work for me. 

-  `git clone git@github.com:jpbarrette/curlpp.git`

Now before going the next step, i added below lines into `CMakeLists.txt`
```
set_target_properties(myTarget PROPERTIES
    CXX_STANDARD 11
    CXX_STANDARD_REQUIRED ON
    CXX_EXTENSIONS OFF
)
```
- `./autogen.sh`

- `./configure`

- `make` // Got the error at this line.

**Comment by jpbarrette** [comment]
Ok, just to clarify: @Shravan40 was using cmake building tool to build curlpp. It means that he's using cmake to create the necessary Makefiles. However, from what you are saying you are using the autotools build tools (by running the autogen.sh/configure script) to generate the Makefiles. So, changing anything in the cmakelists.txt doesn't change anything since it's not used if you use autotools.

NOTE: Both configurations are available on this project, but I'm must say that autotools were the principal build tool maintained on this project. I think I'll slowly transition the project to use cmake and then remove autotools from this project, but I'm not yet ready to do so.

Anyway, if you want to use autotools to generate the Makefiles (which is the officially maintained process), you should use the following branch: 

https://github.com/jpbarrette/curlpp/tree/distributions-fixes-ubuntu

This branch "should" (I hope very much so), be fixing the c++11 compilation problems.

**Comment by jpbarrette** [comment]
@Shravan40 : BTW, as it is mentionned in issue https://github.com/jpbarrette/curlpp/issues/25 you might have problem compiling example18, but it's not a problem unless you want to use the boost library (I'll look into this specific problem next week).

**Comment by Bastian82** [comment]
Hi,
I have the same issue (exactly the same) using CMake. So i tried autotools: (./autogen.sh && ./configure && ./make) but it's failing on the same syntax issue for me:
https://gist.github.com/Bastian82/926a56493fc581c11df9eb3260cf4880

`In file included from ../../../include/utilspp/Functors.hpp:27:0,
                 from ../../../include/curlpp/internal/../Types.hpp:34,
                 from ../../../include/curlpp/internal/CurlHandle.hpp:31,
                 from CurlHandle.cpp:25:
../../../include/utilspp/functor/Functor.hpp:59:28: error: expected ')' before '<' token
     Functor(std::unique_ptr<Impl> impl) 
^`

but even before that there is issue with nullprt looks like no c++0x flag being used:

`make[3]: Entering directory `/home/grzempek/git/curlpp/src/curlpp/internal'
/bin/bash ../../../libtool --silent  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../../../include/curlpp  -I../../../include/curlpp -I../../../include/curlpp/internal -I../../../include  -I../  -g  -W -Wall -Werror    -I/usr/include -MT CurlHandle.lo -MD -MP -MF .deps/CurlHandle.Tpo -c -o CurlHandle.lo CurlHandle.cpp
CurlHandle.cpp:73:2: error: identifier 'nullptr' is a keyword in C++11 [-Werror=c++0x-compat]
  : mException(nullptr)
^`

I added global varialbe in Makefile:
XXFLAGS = -std=c++0x -g  -W -Wall -Werror    -I/usr/include
 
but no luck, the same issue..

**Comment by jpbarrette** [comment]
I just checked-in some changes in "develop" branch. Those changes removes autotools configuration and fixes a lot of issues for cmake's configuration. Can you please try this branch please?

**Comment by jpbarrette** [comment]
New release (v0.8.0) should fix your issue
