### ISSUE TITLE
Incorrect char buffer in WriteFunctionFunctor call back

### ISSUE THREAD

**Issue by aarunuraa** [jpbarrette/curlpp#32]
When receiving large JSON data set as multiple chunks via WriteFunctionFunctor callback, I notice incorrect/unprocessed char* ptr being returned whose size is much more than size X nmemb. The callback signature for WriteFunctionFunctor is as below.
typedef utilspp::Functor< 
		size_t, 
		TYPE_LIST_3(char*, size_t, size_t)> WriteFunctionFunctor
I am attaching the original JSON file and the file written as received via multiple WriteFunctionFunctor callbacks. 

Please compare the attached files and you could notice an unprocessed or incorrect JSON formation inbetween.

Also you could see a '0' character at last in the receivedJSON which shows the HTTP Chunk Encoding is not properly processed(not being removed which marks the end of data/HTTP response) before being returned to the callback function.

[OriginalJSON.txt](https://github.com/jpbarrette/curlpp/files/678451/OriginalJSON.txt)
[JSONReceivedOverMultipleCallbacks.txt](https://github.com/jpbarrette/curlpp/files/678452/JSONReceivedOverMultipleCallbacks.txt)

**Comment by jpbarrette** [comment]
Thanks for the report. I'll try to have a look as soon as possible.

**Comment by jpbarrette** [comment]
Also, can you send some code that would repro the problem?

**Comment by aarunuraa** [comment]
A slightly modified version of Example 05. Libcurl version is 7.18.0 and cURLpp version 0.7.3 . This issue occurs only with big JSON data such as the one attached(OriginalJSON.txt). When trying to GET this JSON(approx 34K bytes) using the following example I noticed some unprocessed/incorrect response data in Char* 

#include <cstdlib>
#include <cstring>

#include <curlpp/cURLpp.hpp>
#include <curlpp/Easy.hpp>
#include <curlpp/Options.hpp>
#include <curlpp/Exception.hpp>


size_t m_Size = 0;
std::string m_responseJSON;


// Callback must be declared static, otherwise it won't link...
size_t WriteMemoryCallback(char* ptr, size_t size, size_t nmemb)
{

    int ret;
    std::string output ( ptr );
    ret = size*nmemb;
    std::cout << "<" <<output.length()<<","<<ret<<">"<<std::endl;
    m_responseJSON+=output;
    m_Size+=ret;
    return ret;
};


void print()
{
    std::cout << "Size: " << m_Size << std::endl;
    std::cout << "Content: " << std::endl << m_responseJSON << std::endl;
}


int main(int argc, char *argv[])
{
    if(argc != 2)
    {
        std::cerr << "Example 05: Wrong number of arguments" << std::endl
            << "Example 05: Usage: example05 url"
            << std::endl;
        return EXIT_FAILURE;
    }
    char *url = argv[1];

    try
    {
        curlpp::Cleanup cleaner;
        curlpp::Easy request;
        // Set the writer callback to enable cURL
        // to write result in a memory area
        curlpp::types::WriteFunctionFunctor functor(WriteMemoryCallback);
        curlpp::options::WriteFunction *test = new curlpp::options::WriteFunction(functor);
        request.setOpt(test);

        // Setting the URL to retrive.
        request.setOpt(new curlpp::options::Url(url));        
        request.setOpt(new curlpp::options::Verbose(true));

        request.perform();

        print();
    }
    catch ( curlpp::LogicError & e )
    {
        std::cout << e.what() << std::endl;
    }
    catch ( curlpp::RuntimeError & e )
    {
        std::cout << e.what() << std::endl;
    }
}

**Comment by jpbarrette** [comment]
Well, your write callback function has an obvious problem: You create a string without taking size*nmemb into consideration. If I'm not mistaken the buffer is preallocated and reused through many calls. Also, as mentionned on [libcurl's](https://curl.haxx.se/libcurl/c/CURLOPT_WRITEFUNCTION.html) documentation:

> The data passed to this function will not be zero terminated!

This means that unless you read only the number of bytes given by size*nmemb, you might endup with characters which belong to previous reads.

std::string has a constructor that takes a pair of iterators: 

    std::string output (ptr, ptr+(size*nmemb));

So here's a potential fix (haven't tried it):

    size_t WriteMemoryCallback(char* ptr, size_t size, size_t nmemb)
    {
         int ret;
         std::string output (ptr, ptr+(size*nmemb));
         ret = size*nmemb;
         std::cout << "<" <<output.length()<<","<<ret<<">"<<std::endl;
         m_responseJSON+=output;
         m_Size+=ret;

         return ret;
     };

Please reopen this issue if it doesn't solve your problem

**Comment by aarunuraa** [comment]
Ya makes sense, Thanks for the feedback.

**Comment by aarunuraa** [comment]
I tried changing the line to 
`std::string` output (ptr, (size*nmemb));  `
and this solves the issue originally seen
Thanks for your support and feedback

**Comment by jpbarrette** [comment]
I've modified the code sample above to reflect your fix
