### ISSUE TITLE
Undefined ref curlpp::InfoTypeConverter

### ISSUE THREAD

**Issue by abhiguru** [jpbarrette/curlpp#33]
Trying to use DeepDetect which has a deps on curlpp

I install curlpp thru apt-get and removed and built (lib not the examples) from source using make and make install but I keep getting the same error in linking stage of DeepDetect 

 In function `curlpp::Info<(CURLINFO)2097154, long>::get(curlpp::Easy&)':
/usr/include/curlpp/Info.inl:39: undefined reference to `curlpp::InfoTypeConverter<long>::get(curlpp::Easy&, CURLINFO, long&)'
../src/libddetect.a(tflib.cc.o): In function `curlpp::Info<(CURLINFO)2097154, long>::get(curlpp::Easy&)':
/usr/include/curlpp/Info.inl:39: undefined reference to `curlpp::InfoTypeConverter<long>::get(curlpp::Easy&, CURLINFO, long&)'
../src/libddetect.a(xgbinputconns.cc.o): In function `curlpp::Info<(CURLINFO)2097154, long>::get(curlpp::Easy&)':
/usr/include/curlpp/Info.inl:39: undefined reference to `curlpp::InfoTypeConverter<long>::get(curlpp::Easy&, CURLINFO, long&)'
/usr/include/curlpp/Info.inl:39: undefined reference to `curlpp::InfoTypeConverter<long>::get(curlpp::Easy&, CURLINFO, long&)'

Any pointers would be helpful

**Comment by MartinThoma** [comment]
I also get this after

```
$ sudo apt-get remove libcurlpp0
$ git clone https://github.com/jpbarrette/curlpp.git
$ cd curlpp
$ cmake .
$ sudo make install
```

**Comment by jpbarrette** [comment]
Just to be safe, if you have this problem, please have a look at @MartinThoma comment on issue https://github.com/beniz/deepdetect/issues/126#issuecomment-284534843
