### ISSUE TITLE
curlpp-config doesn't work

### ISSUE THREAD

**Issue by equal-l2** [jpbarrette/curlpp#34]
Platform: macOS 10.12.3
Version:`0.7.4`

`curlpp-config` doesn't work and abort with the error:

```
/usr/local/bin/curlpp-config: /bin/sh^M: bad interpreter: No such file or directory
```

I'm using homebrew, but this problem also occurs with manual build.

**Comment by jpbarrette** [comment]
I know it's not working if you use CMake building system, but it does work if you use autotools (./configure && make && make install). 

I'm working this week on having those scripts (curlpp-config, curlpp.pc) fixed. I'll let you know

**Comment by equal-l2** [comment]
I've noticed HEAD works, but release 0.7.4 doesn't work anyway.

Both homebrew and I do use autotools for building release 0.7.4 .

**Comment by equal-l2** [comment]
Do you tell which commit fixes this problem, so that I can patch the release?

**Comment by jpbarrette** [comment]
Interesting. Do you know why it didn't work the first time?

**Comment by equal-l2** [comment]
All I noticed are,
- `curlpp-config` doesn't work because of newline format (CRLF instead of LF)
- My automake (0.15) seems to be newer than yours (probably 0.14.1)

**Comment by jpbarrette** [comment]
Yes, I think I did screw up the newline format when I was working on
windows. I'll check how to make sure it doesn't happen again.

**Comment by jpbarrette** [comment]
So, I just did some work to remove all autotools scripts from the project. I switched completely the build system to cmake. Could you help me by trying the branch https://github.com/jpbarrette/curlpp/tree/feature/curlpp-config-fixes ?

**Comment by equal-l2** [comment]
I've tried the branch.

It seems not to install `libcurlpp.dylib` (`dylib` is shared library for macOS) in anywhere.

Can you add a functionality test (e.g. build `example00.cpp` and run) to travis?
That will show you whether the problem occurs only on my environment or not.

**Comment by jpbarrette** [comment]
I think that's the next step. Examples are part of the project, but they
are built when we are building the project. This means that it doesn't test
the installation process. I might add them into a different target which
goes after the install.

**Comment by equal-l2** [comment]
Anyway, curlpp-config works well, except the library is not in the place it directs.

**Comment by jpbarrette** [comment]
I've just submitted some changes in https://github.com/jpbarrette/curlpp/tree/feature/curlpp-config-fixes

This ensures that examples are built as a second stage requiring curlpp to be installed. Everything seems to work (and the library is properly installed)

**Comment by equal-l2** [comment]
Finally it works successfully!
Thank you for your work.

By the way, `curlpp-config --cflags` currently doesn't include any standard specification flag (e.g. `-std=c++11`).
This prevent source uses curlpp from compiling when I use clang (macOS default compiler), because curlpp uses `<functional>` header, which is added by C++11.
Would you add any standard specification flag in `--cflags`?

**Comment by jpbarrette** [comment]
> Would you add any standard specification flag in `--cflags`?

That's a very good question, I need to check this.

**Comment by jpbarrette** [comment]
I've stumbled upon a debian's bug report that discuss that issue: https://bugzilla.gnome.org/show_bug.cgi?id=755750

> Debian seem to have put -std=c++11 in the pkg-config file for its libsigc++ package:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=800399
>
> That is very unwise and inconvenient for application developers, particularly as they now start to use C++14. 

I tend to agree with that statement. I think it's rather the library users to make sure they are supporting at least c++11, but free to use any newer version.
