### ISSUE TITLE
Make visual Studio Community Project files.

### ISSUE THREAD

**Issue by AraHaan** [jpbarrette/curlpp#36]
On Windows you do not need a lincense to use Visual Studio Community. With Community you get everything that is in all the other editions of visual Studio for free as well. So, all the more reasons to make one. I could even Pull request some if you would like because I use the latest Update to Visual Studio Community 2015.

**Comment by jpbarrette** [comment]
Well, cmake (what we use) will generate those project files for you. You can follow the example here: https://cognitivewaves.wordpress.com/cmake-and-visual-studio/#execute-cmake. But mostly make sure you have cmake installed (https://cmake.org/download/) and execute the following commands: 

```
cd /path/to/curlpp/
mkdir build
cd build
cmake -G "Visual Studio 14 2015 Win64" ../
```

**Comment by AraHaan** [comment]
I already have cmake and make and even nmake installed so it should be fine.
