### ISSUE TITLE
curlpp configure.ac wipes out CXX optimisation flags

### ISSUE THREAD

**Issue by amitkc** [jpbarrette/curlpp#38]
I've noticed that the autotools build system that comes with 0.7.3 deliberately passes CXXFLAGS through a sed filter to remove anything matching -O[0-9]*. Why is this? I was attempting to pass -O3 as part of my configure for a powerpc-linux cross compile and was surprised to see that CFLAGS were preserved but CXX was not.

**Comment by jpbarrette** [comment]
I must admit that I can't figure out the reason why I did that change. Anyway on new versions, we are no longer on autotools, but CMake, and there's no such things in the new versions. 

Is it an option for you got use the newer functions?

**Comment by amitkc** [comment]
I am not a huge fan of CMake but using the newer version might be an option. I can work around the issue on 0.7.3 and will do so for the short term.  But I will review the change logs to see if 0.8 offers performance improvements without API changes. If so, I'll maybe swallow my dislike of CMake and do some test builds.  Thanks for the  quick reply.

**Comment by jpbarrette** [comment]
Just so that you know 0.8 has API changes. Mostly it's not C++14 compliant is no longer uses boost. So I hope that it won't require much work on your part to update to 0.8.

I'll close that issue for now, but feel free to reopen if you need more.
