### ISSUE TITLE
curlpp.pc: doesn't contain version number

### ISSUE THREAD

**Issue by sim590** [jpbarrette/curlpp#47]
The resulting `curlpp.pc` file doesn't contain a version number after using `cmake` prior to build curlpp. I suspect that this explains why my package cannot require curlpp for version >= 0.8.1 appropriately. I am using autotools for building. See the following:
```
configure: error: Package requirements (curlpp >= 0.8.1) were not met:

Requested 'curlpp >= 0.8.1' but version of curlpp is

Consider adjusting the PKG_CONFIG_PATH environment variable if you
installed software in a non-standard prefix.

Alternatively, you may set the environment variables CURLPP_CFLAGS
and CURLPP_LIBS to avoid the need to call pkg-config.
See the pkg-config man page for more details.
```
Even though you [seem to have dropped autotools as build system][drop-at], I think that other packages using other build system should still be able to require curlpp for a specific subset of versions. This means, you should fix the `curlpp.pc` file if I'm not mistaken.

[drop-at]: https://github.com/jpbarrette/curlpp/issues/34#issuecomment-276893343

**Comment by jpbarrette** [comment]
Fixed by commit https://github.com/jpbarrette/curlpp/commit/7e3df5ee9008a4db60d0e4df0112fbd2d19a4708 in "[develop](https://github.com/jpbarrette/curlpp/tree/develop)" branch.
