### ISSUE TITLE
Cross Compile Error

### ISSUE THREAD

**Issue by jiangcy1994** [jpbarrette/curlpp#5]
Cross Compiled by arm-none-linux-gnueabi-gcc it seems that taking -I/usr/local/include and -L/usr/local/lib in Makefile is quite harmful for cross compile.Hope for improvement.

**Comment by jpbarrette** [comment]
I don't mind fixing this, but I would like more details if possible. I'm not quite sure I get the point.

**Comment by AraHaan** [comment]
Would using the microsoft compilers on Windows for for this too? Also what about API's that work with json like requests would it work for them as well?

**Comment by jpbarrette** [comment]
Sorry @AraHaa, but your comment has nothing to do with the current issue. Please reopen a different issue.
