### ISSUE TITLE
Silent GET request

### ISSUE THREAD

**Issue by dima91** [jpbarrette/curlpp#53]
is it possible to perform a GET request to a rest server, doesn't show the response payload on stdout but get the response code?
with ostringstream I can't analyze response code but with `perform` method it show me response on stdout.

**Comment by jpbarrette** [comment]
examples/example04.cpp has an example on how to get the response code. For doing the download request without getting the body, `NoBody` is the option for you:

(non-tested code following)

    curlpp::Cleanup cleaner;
    curlpp::Easy request;
    
    request.setOpt(curlpp::Options::Url("http://yoururl.com"));
    request.setOpt(curlpp::Options::NoBody);
    
    request.perform();
    std::cout << "Response code: " 
    		<< curlpp::infos::ResponseCode::get(request) 
    		<< std::endl;

**Comment by jpbarrette** [comment]
I'm closing this issue, but reopen if you think it doesn't answer your question.

**Comment by dima91** [comment]
in that example i didn't find any refers to NoBody option and if I try to compile this code (from example04.cpp)
```
curlpp::Cleanup cleaner;
		curlpp::Easy request;

		using namespace curlpp::Options;
		request.setOpt(NoBody);
		request.setOpt(Verbose(true));
		request.setOpt(Url("http://myurl.com"));

		request.perform();

		std::string effURL;
		curlpp::infos::EffectiveUrl::get(request, effURL);
		std::cout << "Effective URL: " << effURL << std::endl;

		//other way to retreive URL
		std::cout << std::endl 
			<< "Effective URL: " 
			<< curlpp::infos::EffectiveUrl::get(request)
			<< std::endl;

		std::cout << "Response code: " 
			<< curlpp::infos::ResponseCode::get(request) 
			<< std::endl;

		std::cout << "SSL engines: " 
			<< curlpp::infos::SslEngines::get(request)
			<< std::endl;
```
the compilation fails with this error
```
example04.cpp: In function ‘int main(int, char**)’:
example04.cpp:57:24: error: expected primary-expression before ‘)’ token
   request.setOpt(NoBody);
```
